//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication44.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourse : StudentCourseBase
    {
        public StudentCourse()
        {
            this.SetStudentInfo(new HashSet<StudentInfo>());
        }
    }

    internal class StudentInfo
    {
    }
}
