//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentInfo
    {
        public int StudentId { get; set; }
        public string studentName { get; set; }
        public string studentMobile { get; set; }
        public string studentAddress { get; set; }
        public string studentDept { get; set; }
    
        public virtual Student_Course Student_Course { get; set; }
    }
}
